#!/bin/sh
REPO="$HOME"/archix
SCRIPTS="$REPO"/scripts
. "$SCRIPTS"/pre_install

. "$SCRIPTS"/iso

. "$SCRIPTS"/vars

cp -r "$REPO" /mnt/root

if [ "$ARTIX" = true ];then
    CHROOT=artix-chroot;else
    CHROOT=arch-chroot
fi

$CHROOT /mnt "$HOME"/archix/scripts/chroot
$CHROOT /mnt /usr/bin/runuser -u "$USERNAME" -- /home/"$USERNAME"/archix/scripts/chroot_user
$CHROOT /mnt "$HOME"/archix/scripts/chroot_post

rm -rf /mnt/root/archix /mnt/home/"$USERNAME"/archix

printf "\n\nINSTALL COMPLETE! - Press enter to reboot\n\n"
read
reboot
