#!/bin/sh

case "$1" in
    start)
        modprobe zram
        zramctl /dev/zram0 --algorithm lz4 --size "$(($(grep -Po 'MemTotal:\s*\K\d+' /proc/meminfo)/2))KiB"
        mkswap -U clear /dev/zram0
        swapon --discard --priority 100 /dev/zram0
        ;;
    stop)
        swapoff /dev/zram0
        modprobe -r zram
        ;;
esac
