#!/bin/bash
. "$HOME"/archix/scripts/vars

cd "$HOME" || { printf "Failed to cd into %s" "$HOME" ; exit 1 ; }

#config
mv "$HOME"/archix/config "$HOME"/.config
fish -c 'set -U fish_greeting'
#if [ "$ARTIX" = true ];then
#    printf "[Desktop Entry]\nExec=/usr/bin/pkill -u \"\$USER\" -x pipewire\|wireplumber ; /usr/bin/pidwait -u \"\$USER\" -x pipewire\|wireplumber ; /usr/bin/pipewire & /usr/bin/pipewire-pulse & /usr/bin/sleep 1 ; /usr/bin/wireplumber &\nName=Pipewire\nType=Application\nX-KDE-AutostartScript=true\n" > ~/.config/autostart/pipewire.desktop
#fi
#Install Thumbfast
mkdir "$HOME"/.config/mpv/scripts
cd "$HOME"/.config/mpv/scripts || { printf "Failed to cd into %s/.config/mpv/scripts" "$HOME" ; exit 1 ; }

#Download OSC and thumbnailer
curl -O 'https://raw.githubusercontent.com/po5/thumbfast/5fefc9b8e995cf5e663666aa10649af799e60186/player/lua/osc.lua'
curl -O 'https://raw.githubusercontent.com/po5/thumbfast/master/thumbfast.lua'

cd "$HOME" || { printf "Failed to cd into %s" "$HOME" ; exit 1 ; }

if ! [ -d "$HOME"/Games ];then
    mkdir Games
fi

flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo

#Configure dinit user services for pipewire
mkdir -p "$HOME"/.config/dinit.d/boot.d
ln -s /etc/dinit.d/user/pipewire /etc/dinit.d/user/pipewire-pulse /etc/dinit.d/user/wireplumber -t "$HOME"/.config/dinit.d/boot.d/

#Paru
RAM=$(grep -Po 'MemTotal:\s*\K\d+' /proc/meminfo)

if [ "$RAM" -ge 8000000 ];then #prefer compilation if enough memory is available
    PARU="paru";else
    PARU="paru-bin"
fi

git clone https://aur.archlinux.org/"$PARU".git
cd "$PARU" || { printf "Failed to cd into %s" "$PARU" ; exit 1 ; }
makepkg -si --noconfirm
cd "$HOME" || { printf "Failed to cd into %s" "$HOME" ; exit 1 ; }
rm -rf "$PARU"
mkdir "$HOME"/.config/paru/

cp /etc/paru.conf .config/paru/
sed -i -e 's/#Clean/Clean/' -i -e 's/#UpgradeMenu/UpgradeMenu/' -i -e 's/#News/News/' "$HOME"/.config/paru/paru.conf
if [ "$DOAS" = true ];then
    sed -i -e 's/#\[bin\]/\[bin\]/' -i -e 's,#Sudo = doas,Sudo = /bin/doas,' "$HOME"/.config/paru/paru.conf
fi

paru -S --needed --noconfirm brave-bin
