#!/bin/bash
. "$HOME"/archix/scripts/vars

INSTALL="pacman -S --needed --noconfirm --disable-download-timeout"

if [ -f /usr/share/libalpm/hooks/90-mkinitcpio-install.hook ];then
    mv /usr/share/libalpm/hooks/90-mkinitcpio-install.hook /usr/share/libalpm/hooks/90-mkinitcpio-install.hook.disabled
fi
if [ -f /usr/share/libalpm/hooks/60-mkinitcpio-remove.hook ];then
    mv /usr/share/libalpm/hooks/60-mkinitcpio-remove.hook /usr/share/libalpm/hooks/60-mkinitcpio-remove.hook.disabled
fi

#Pacman Config
sed -i -e 's/#Color/Color/' -i -e '/Color/a ILoveCandy' -i -e 's/#Verbose/Verbose/' -i -e 's/#Parallel/Parallel/' -i -e "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf

if [ "$ARTIX" = true ];then
   sed -i -z -e 's,\[galaxy\]\nInclude = /etc/pacman.d/mirrorlist,\[galaxy\]\nInclude = /etc/pacman.d/mirrorlist,' -i -z -e 's,\[lib32\]\n#Include = /etc/pacman.d/mirrorlist,\[lib32\]\n#Include = /etc/pacman.d/mirrorlist\n\n#Arch Repos\n\n#\[extra-testing\]\n#Include = /etc/pacman.d/mirrorlist-arch\n\n#\[extra\]\n#Include = /etc/pacman.d/mirrorlist-arch\n\n#\[multilib-testing\]\n#Include = /etc/pacman.d/mirrorlist-arch\n\n#\[multilib\]\n#Include = /etc/pacman.d/mirrorlist-arch,' /etc/pacman.conf
   pacman -Syu --needed --noconfirm artix-archlinux-support
   sed -i -e "/\[lib32\]/,/Include/"'s/^#//' -i -e "/\[extra\]/,/Include/"'s/^#//' /etc/pacman.conf
   pacman-key --populate
fi

#Sort Mirrors
pacman -Syu --noconfirm rate-mirrors
mv /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.bak
if [ "$ARTIX" = true ];then
    #rate-mirrors --protocol https --concurrency 1 --max-mirrors-to-output 5 --disable-comments-in-file --allow-root --save /etc/pacman.d/mirrorlist artix
    mv /etc/pacman.d/mirrorlist-arch /etc/pacman.d/mirrorlist-arch.bak
    rate-mirrors --protocol https --concurrency 1 --max-mirrors-to-output 5 --disable-comments-in-file --allow-root --save /etc/pacman.d/mirrorlist-arch arch
    #sed '/http:/d' /etc/pacman.d/mirrorlist-arch.bak | sed 's/#//g' | rankmirrors -vwn 5 - > /etc/pacman.d/mirrorlist #Rank HTTPS mirrors without modifying mirrorlist.pacnew
else
    rate-mirrors --protocol https --concurrency 1 --max-mirrors-to-output 5 --disable-comments-in-file --allow-root --save /etc/pacman.d/mirrorlist arch
    #reflector --sort rate -c "$(curl ifconfig.co/country-iso)",* -p https -a 48 -f 5 --save /etc/pacman.d/mirrorlist
fi

if ! [ -e /etc/pacman.d/mirrorlist ];then
    mv /etc/pacman.d/mirrorlist.bak /etc/pacman.d/mirrorlist
    printf "\nTHERE WAS AN ERROR WITH MIRRORLIST GENERATION. PLEASE SORT MIRRORLIST MANUALLY AFTER INSTALL.\n"
    sleep 5
fi

#Update to get repos
pacman -Syu --noconfirm

#Snapper Setup
$INSTALL snapper
mount -o subvolid=5 "$ROOT_PART" /mnt
btrfs subvolume create /mnt/@.snapshots
umount /mnt
mount --mkdir -o defaults,noatime,subvol=/@.snapshots "$ROOT_PART" /.snapshots
chmod 750 /.snapshots
printf "UUID=%s /.snapshots btrfs defaults,noatime,subvol=/@.snapshots 0 0\n" "$ROOT_UUID" >> /etc/fstab
mv "$HOME"/archix/etc/snapper/configs/root /etc/snapper/configs
mv "$HOME"/archix/etc/conf.d/snapper /etc/conf.d

#Set Language Locale (Needs work)
sed -i "s/#en_US.UTF-8/en_US.UTF-8/" /etc/locale.gen
printf "LANG=en_US.UTF-8\nLC_COLLATE=\"C\"" > /etc/locale.conf
locale-gen

#vconsole
printf "KEYMAP=%s\nFONT=default8x16\n" "$KEYMAP" > /etc/vconsole.conf

# DOWNLOADS #
#Grapics Drivers
if lspci | grep "VGA" | grep -E "Radeon|AMD|ATI";then
   $INSTALL lib32-vulkan-radeon libva-mesa-driver mesa opencl-rusticl-mesa vulkan-icd-loader vulkan-radeon
fi

if lspci | grep "VGA" | grep -E "Intel Corporation|UHD";then
     $INSTALL intel-media-driver lib32-vulkan-intel libva-intel-driver libva-utils mesa opencl-rusticl-mesa vulkan-icd-loader vulkan-intel
fi

if [ "$VM" = true ];then
    $INSTALL vulkan-virtio lib32-vulkan-virtio
fi

#System Packages
cat "$HOME"/archix/packages/system.txt | $INSTALL -

if [ "$LAPTOP" = true ];then
    $INSTALL tlp
fi

#Artix services
if [ "$ARTIX" = true ];then
    cat "$HOME"/archix/packages/artix-services.txt | $INSTALL -
    if [ "$LAPTOP" = true ];then
        $INSTALL tlp-dinit
    fi
fi

#KDE Plasma
cat "$HOME"/archix/packages/plasma.txt | $INSTALL -

pkgfile -u

#Flatpak Setup
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

#Set Timezone
mv /etc/chrony.conf /etc/chrony.conf.bak
curl "https://raw.githubusercontent.com/GrapheneOS/infrastructure/refs/heads/main/etc/chrony.conf" -o /etc/chrony.conf #GrapheneOS Chrony Settings
ln -sf /usr/share/zoneinfo/"$TIMEZONE" /etc/localtime
hwclock --systohc

#Hostname
printf "%s\n" "$HN" > /etc/hostname

#Root Password
if [ -n "$ROOT_PASSWORD" ];then
    printf "root:%s" "$ROOT_PASSWORD" | chpasswd
fi

#User
useradd -mG wheel -s /bin/fish "$USERNAME"
printf "%s:%s" "$USERNAME" "$PASSWORD" | chpasswd

#:wheel permissions (nopasswd)
if [ "$DOAS" = true ];then
    $INSTALL opendoas
    printf "permit nopass :wheel\n" > /etc/doas.conf
    chown -c root:root /etc/doas.conf
    chmod -c 0400 /etc/doas.conf;else
    sed -i "s/# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/" /etc/sudoers
fi

if ! getent group gamemode;then
    groupadd -r gamemode
fi

gpasswd -a "$USERNAME" gamemode

#Set SDDM theme
if [ "$ARTIX" = true ];then
    $INSTALL sddm sddm-kcm
    printf "[Theme]\nCurrent=breeze\n" > /etc/sddm.conf
fi

#Apparmor & Audit Config
sed -i 's/#write-cache/write-cache/' /etc/apparmor/parser.conf
if ! getent group audit;then
    groupadd -r audit
fi
gpasswd -a "$USERNAME" audit
sed -i '/log_group/a log_group = audit' /etc/audit/auditd.conf

#Networkmanager IPv6 Privacy Features
printf "[connection]\nipv6.ip6-privacy=2\n" > /etc/NetworkManager/conf.d/ipv6-privacy-features.conf

#Whonix Machine ID
printf "b08dfa6083e7567a1921a715000001fb\n" > /etc/machine-id
printf "b08dfa6083e7567a1921a715000001fb\n" > /var/lib/dbus/machine-id

#Qemu setup
sed -i -e 's/#unix_sock_group = "libvirt"/unix_sock_group = "libvirt"/' -i -e 's/#unix_sock_ro_perms = "0777"/unix_sock_ro_perms = "0777"/' -i -e 's/#unix_sock_rw_perms = "0770"/unix_sock_rw_perms = "0770"/' /etc/libvirt/libvirtd.conf
sed -i 's/#group.*/group = "libvirt"/' /etc/libvirt/qemu.conf
sed -i 's/#firewall_backend = "nftables"/firewall_backend = "iptables"/' /etc/libvirt/network.conf
gpasswd -a "$USERNAME" libvirt

#Makepkg Optimisations
sed -i -e "s/#MAKEFLAGS.*/MAKEFLAGS=\"-j\$(nproc)\"/" -i -e 's/(xz/(xz --threads=0/' -i -e 's/(zstd/(zstd --threads=0/' -i -e 's/-march=x86-64 -mtune=generic/-march=native/' -i -e 's/#RUSTFLAGS.*/RUSTFLAGS="-C opt-level=3 -C target-cpu=native"/' -i -e 's/(bzip2/(lbzip2/' -i -e 's/(gzip/(pigz/' /etc/makepkg.conf
if [ "$DOAS" = true ];then
     sed -i 's,#PACMAN_AUTH=(),PACMAN_AUTH=(/bin/doas),' /etc/makepkg.conf
fi

#Import sysctl settings
mv "$HOME"/archix/etc/sysctl.d /etc/

#Zram & Swap
if [ "$ARTIX" = true ];then
    mv "$HOME"/archix/etc/dinit.d/* /etc/dinit.d
else
    $INSTALL zram-generator
    mv "$HOME"/archix/etc/systemd/zram-generator.conf.d /etc/systemd
fi

mv "$HOME"/archix/etc/conf.d/pacman-contrib /etc/conf.d

#Allows freshclam to work
touch /var/log/clamav/freshclam.log
chmod 600 /var/log/clamav/freshclam.log
chown clamav /var/log/clamav/freshclam.log
freshclam

#Hardened /tmp
if [ "$ARTIX" = true ];then
    cp /usr/lib/dinit.d/dinit-user-spawn /usr/lib/dinit.d/tmpmount -t /etc/dinit.d
    cp /usr/lib/dinit/tmpmount /etc/dinit.d/scripts/
    sed -i 's,/usr/lib/dinit/tmpmount,/etc/dinit.d/scripts/tmpmount,' /etc/dinit.d/tmpmount
    sed -i "s.tmpfs /tmp.tmpfs /tmp -o defaults,nosuid,nodev." /etc/dinit.d/scripts/tmpmount
fi

#Firewall settings
ufw default deny incoming
ufw default allow outgoing
ufw enable

cp -r "$HOME"/archix /home/"$USERNAME"
chown -R "$USERNAME": /home/"$USERNAME"/archix
