#!/bin/sh
. "$HOME"/archix/Scripts/vars

#Paru
git clone https://aur.archlinux.org/paru.git
cd paru
makepkg -si --noconfirm
cd
rm -rf paru/

if ! [ -d "$HOME"/.config ];then
    mkdir "$HOME"/.config
fi
mkdir .config/paru/

cp /etc/paru.conf .config/paru/
sed -i -e 's/#Clean/Clean/' -i -e 's/#UpgradeMenu/UpgradeMenu/' -i -e 's/#News/News/' .config/paru/paru.conf
if [ "$DOAS" = true ];then
    sed -i -e 's/#\[bin\]/\[bin\]/' -i -e 's,#Sudo = doas,Sudo = /bin/doas,' .config/paru/paru.conf
fi

if [ "$ARTIX" != true ];then
    paru -S --needed --noconfirm librewolf-bin;else
    if [ "$DOAS" = true ];then
    doas pacman -S --needed --noconfirm librewolf;else
    sudo pacman -S --needed --noconfirm librewolf
    fi
fi

#KDE Startup files
if ! [ -d "$HOME"/.config/autostart ];then
    mkdir "$HOME"/.config/autostart
fi
if [ "$ARTIX" = true ];then
    printf "[Desktop Entry]\nExec=/usr/bin/pkill -u \"\$USER\" -x pipewire\|wireplumber ; /usr/bin/pidwait -u \"\$USER\" -x pipewire\|wireplumber ; /usr/bin/pipewire & /usr/bin/pipewire-pulse & /usr/bin/sleep 1 ; /usr/bin/wireplumber &\nName=Pipewire\nType=Application\nX-KDE-AutostartScript=true" > ~/.config/autostart/pipewire.desktop
fi
printf "[Desktop Entry]\nType=Application\nName=Apparmor Notify\nComment=Notify User of Apparmor Denials\nTryExec=aa-notify\nExec=aa-notify -p -s 1 -w 60 -f /var/log/audit/audit.log\nStartupNotify=false\nNoDisplay=true" > "$HOME"/.config/autostart/apparmor-notify.desktop

#config
mv "$HOME"/archix/dotfils/config/* "$HOME".config/
#Install Thumbfast
mkdir "$HOME".config/mpv/scripts/
cd "$HOME".config/mpv/scripts/
#Standard OSC
wget 'https://raw.githubusercontent.com/po5/thumbfast/5fefc9b8e995cf5e663666aa10649af799e60186/player/lua/osc.lua'
wget 'https://raw.githubusercontent.com/po5/thumbfast/master/thumbfast.lua'
cd
if [ "$STEAM" = true ] && ! [ -d "$HOME"/Games ];then
    mkdir Games
fi
mv "$HOME"/archix/dotfiles/shells/bash/* "$HOME"
if [ "$SHELL" = fish ];then
    fish -c 'set -U fish_greeting'
    mv "$HOME"/archix/dotfiles/shells/config.fish ~/.config/fish/
fi
