#!/bin/sh
. "$HOME"/archix/scripts/vars

#password :wheel perms
if [ "$DOAS" = true ];then
    sed -i "s/nopass/persist/" /etc/doas.conf;else
    sed -i -e "s/%wheel ALL=(ALL:ALL) NOPASSWD: ALL/# %wheel ALL=(ALL:ALL) NOPASSWD: ALL/" -i -e "s/# %wheel ALL=(ALL:ALL) ALL/%wheel ALL=(ALL:ALL) ALL/" /etc/sudoers
fi

#Allows freshclam to work (may only be needed for systemd)
touch /var/log/clamav/freshclam.log
chmod 0640 /var/log/clamav/freshclam.log

#Hardened /tmp
if [ "$ARTIX" = true ] && [ "$INIT" = dinit ];then
    cp /usr/lib/dinit.d/tmpfs /etc/dinit.d
    sed -i 's|command.*|command   = /bin/mount -t tmpfs tmpfs /tmp -o defaults,nodev,noexec,nosuid|' /etc/dinit.d/tmpfs;else
    printf "tmpfs /tmp tmpfs defaults,nodev,noexec,nosuid 0 0\n" >> /etc/fstab
fi

#Firewall settings
ufw status
ufw enable
ufw default deny incoming
ufw default allow outgoing
ufw allow http
ufw allow https
ufw allow dns
ufw allow mdns
ufw allow 631
ufw allow qbittorrent

# Regenerate the initramfs and grub config in case they've been updated
mkinitcpio -P
grub-mkconfig -o /boot/grub/grub.cfg

#Init Services
if [ "$VM" = true ];then
    QEMU=" libvirtd virtlogd"
fi
if [ "$LAPTOP" = true ];then
    TLP=" tlp"
fi

SERVICES="NetworkManager ufw chronyd sddm $CRON earlyoom apparmor auditd$QEMU$TLP"

if [ "$ARTIX" != true ];then
    SERVICES="cups clamav-freshclam $SERVICES"
    systemctl enable $SERVICES
else
    SERVICES="cupsd freshclam $SERVICES"
    for SERVICE in $SERVICES;do
        if [ "$INIT" = dinit ];then
            INITSTART="ln -s /etc/dinit.d/$SERVICE /etc/dinit.d/boot.d/"
        elif [ "$INIT" = runit ];then
            INITSTART="ln -s /etc/runit/sv/$SERVICE /run/runit/service/"
        elif [ "$INIT" = openrc ];then
            INITSTART="rc-update add $SERVICE default"
        elif [ "$INIT" = s6 ];then
            INITSTART="touch /etc/s6/adminsv/default/contents.d/$SERVICE"
        fi
        $INITSTART
    done
fi

#if [ "$grbtrfs" = y ];then
#    if [ "$init" = dinit ];then
#        printf "type            = process\nenv-file        = /etc/default/grub-btrfs/config\ncommand         = /usr/bin/grub-btrfsd --syslog /.snapshots\nsmooth-recovery = true" | sudo tee /etc/dinit.d/grub-btrfsd
#        dinitctl enable grub-btrfsd;else
#        systemctl enable grub-btrfsd
#    fi
#fi

if [ "$INIT" = s6 ];then
    s6-db-reload
fi

if [ "$VM" = true ];then
    virtqemud &
    virtnetworkd &
    virsh net-autostart default
fi
