#!/bin/sh
. "$HOME"/archix/scripts/vars

#Speed up install
sed -i 's/^#ParallelDownloads/ParallelDownloads/' /etc/pacman.conf

#PARTITION DISKS
umount -AR /mnt

wipefs -af "$INSTALL_DISK"

#Create GPT table and BIOS/UEFI partition
printf "g\nn\n\n\n+1G\nt\n\nEFI System\nw" | fdisk -W always "$INSTALL_DISK"
printf "n\n\n\n\n\nt\n\nLinux Filesystem\nw" | fdisk -W always "$INSTALL_DISK"

if printf "%s" "$INSTALL_DISK" | grep -q nvme;then
    PARTITION="$INSTALL_DISK"p;else
    PARTITION="$INSTALL_DISK"
fi
ESP_PART="$PARTITION"1
ROOT_PART="$PARTITION"2

#FORMAT FS
mkfs.fat -F 32 -n EFI "$ESP_PART"

if [ "$LUKS" = true ];then
    printf "%s" "$LUKS_PASSWORD" | cryptsetup luksFormat "$ROOT_PART" -
    printf "%s" "$LUKS_PASSWORD" | cryptsetup luksOpen "$ROOT_PART" root -
    CRYPT_ROOT_PART="$ROOT_PART"
    ROOT_PART=/dev/mapper/root
fi
printf "ROOT_PART=%s\n" "$ROOT_PART" >> "$HOME"/archix/scripts/vars
mkfs.btrfs -L Root --checksum sha256 "$ROOT_PART"
MOUNT_OPTS="noatime,compress-force=zstd:1"

###
# May be unneeded as discardable drives will mount with discard=async by default
###
#DISCARD_VALUES=$(lsblk -no TYPE,KNAME,DISC-GRAN,DISC-MAX | sed "/part/d" | grep "$(printf "%s" "$INSTALL_DISK" | cut -d/ -f3)" | awk '$1=="disk"{print ""$3" "$4}' | tr -Cd "[:digit:][:space:]")
#for i in $DISCARD_VALUES;do
#    if [ "$i" = 0 ];then
#        continue
#    fi
#    MOUNT_OPTS="${MOUNT_OPTS},discard=async" #Only adds
#done

#Get UUIDS
sleep 10 #BTRFS takes longer to generate UUIDs, this prevents readings from being blank
if [ "$LUKS" = true ];then
    ROOT_UUID=$(lsblk -oUUID "$ROOT_PART" | sed '/UUID/d')
    CRYPT_PART_UUID=$(lsblk -oUUID "$CRYPT_ROOT_PART" | sed '/UUID/d' | sed "/$ROOT_UUID/d")
    printf "CRYPT_PART_UUID=%s\n" "$CRYPT_PART_UUID" >> "$HOME"/archix/scripts/vars
else
    ROOT_UUID=$(lsblk -oUUID "$ROOT_PART" | sed '/UUID/d')
fi
printf "ROOT_UUID=%s\n" "$ROOT_UUID" >> "$HOME"/archix/scripts/vars

#Make subvolumes
mount -o "$MOUNT_OPTS" "$ROOT_PART" /mnt
for i in $SUBVOLS;do
    btrfs subvolume create /mnt/"$i"
done
umount /mnt

#MOUNT
for SUBVOL in $SUBVOLS;do
    MOUNT_POINT=$(printf "%s" "$SUBVOL_PATHS" | cut -d\  -f1)
    mount --mkdir -o "$MOUNT_OPTS",subvol="$SUBVOL" "$ROOT_PART" "$MOUNT_POINT"
    SUBVOL_PATHS=$(printf "%s" "$SUBVOL_PATHS" | cut -d\  -f 2-)
done

mount --mkdir -o noatime,nodev,noexec,nosuid,fmask=0137,dmask=0027 "$ESP_PART" /mnt/efi

FIRMWARE="linux-firmware linux-firmware-liquidio linux-firmware-marvell linux-firmware-mellanox linux-firmware-nfp linux-firmware-qcom linux-firmware-qlogic"

#Install Base root
if [ "$ARTIX" = true ];then
    basestrap /mnt base base-devel "$INIT"-system $KERNELS $HEADERS $FIRMWARE mkinitcpio networkmanager-"$INIT" iptables-nft wget btrfs-progs git efibootmgr "$CPU"-ucode eukify
    fstabgen -U /mnt >> /mnt/etc/fstab;else
    pacstrap -K /mnt base base-devel $KERNELS $HEADERS $FIRMWARE mkinitcpio networkmanager iptables-nft wget btrfs-progs git efibootmgr "$CPU"-ucode systemd-ukify
    genfstab -U /mnt >> /mnt/etc/fstab
fi
