#!/bin/bash
REPO="$HOME"/archix
VAR_FILE="$REPO"/scripts/vars
if ! [ -f "$VAR_FILE" ];then
    touch "$VAR_FILE"
fi

printf "REPO=%s\n" "$REPO" >> "$VAR_FILE"

pacman-key --init
pacman-key --populate
pacman -Sy --noconfirm mokutil

if mokutil --sb-state | grep "Setup Mode";then
    while :;do
        printf "Detected Secure Boot in setup mode. Configure Secure Boot?\n[y/n]: "

        read -r -r SB

        case "$SB" in
            y)
                printf "SB=true\n" >> "$VAR_FILE"
                break
                ;;
            n)
                break
                ;;
            *)
                printf "Invalid input, try again.\n"
                ;;
        esac
    done
fi

if grep -qi "Artix" /etc/os-release;then
    ARTIX=true
    printf "ARTIX=true\n" >> "$VAR_FILE" 
fi

CHASSIS=$(cat /sys/class/dmi/id/chassis_type)
if [ "$CHASSIS" = 9 ] || [ "$CHASSIS" = 10 ];then
    printf "LAPTOP=true\n" >> "$VAR_FILE"
fi

if lscpu | grep -q "AuthenticAMD";then
    printf "CPU=amd\n" >> "$VAR_FILE"
elif lscpu | grep -q "GenuineIntel";then
    printf "CPU=intel\n" >> "$VAR_FILE"
fi

TIMEZONE=$(curl -s https://ipapi.co/timezone)
COUNTRY=$(printf "%s" "$TIMEZONE" | cut -d/ -f1)
printf "TIMEZONE=%s\nCOUNTRY=%s\n" "$TIMEZONE" "$COUNTRY" >> "$VAR_FILE"

DISKS=$(lsblk -no TYPE,KNAME,SIZE | awk '$1=="disk"{print "/dev/"$2" | "$3}')
while :;do
    printf "From the following, select the disk to install on:\n%s\nDisk name: " "$DISKS"
    read -r INSTALL_DISK
    for DISK in $(printf "%s" "$DISKS" | cut -d\  -f1);do
        if [ "$INSTALL_DISK" = "$DISK" ];then
            VALID_DISK=true
        fi
    done
    if [ "$VALID_DISK" = true ];then
        while :;do
            printf "Install Linux on \"%s\"? THIS WILL FORMAT AND DELETE ALL DATA!\n[y/n]: " "$INSTALL_DISK"
            read -r DRIVE_CONF

            case "$DRIVE_CONF" in

                y)
                    break 2
                    ;;
                n)
                    printf "Returning to drive selection menu...\n\n"
                    unset INSTALL_DISK VALID_DISK
                    break
                    ;;
                *)
                    printf "Invalid input, try again.\n"
                    ;;
            esac
        done;else
        printf "\"%s\" is not a valid installation disk!\n" "$INSTALL_DISK"
    fi
done

WINCHECK_DISKS=$(printf "%s" "$DISKS" | sed "s,$INSTALL_DISK,,")
for DISK in $WINCHECK_DISKS;do
    if efibootmgr "$DISK" | grep -q "Windows Boot Manager";then
        printf "Windows installation detected on %s! Installing refind for dual-boot support...\n" "$DISK"
        REFIND=true
        sleep 5
        break
    fi
done

while :;do
    printf "Encrypt root with LUKS?\n[y/n]: "
    read -r LUKS

    case "$LUKS" in

        y)
            while :;do
                printf "Enter encryption password: "
                read -r LUKS_PASSWORD
                printf "Confirm encryption password: "
                read -r LUKS_PASSWD_CONF
                case "$LUKS_PASSWD_CONF" in

                    "$LUKS_PASSWORD")
                        printf "LUKS=true\nLUKS_PASSWORD=\"%s\"\n" "$LUKS_PASSWORD" >> "$VAR_FILE"
                        break
                        ;;
                    *)
                        printf "PASSWORDS DID NOT MATCH!\n"
                        unset LUKS_PASSWORD LUKS_PASSWD_CONF
                        ;;
                esac
            done
            break
            ;;
        n)
            break
            ;;
        *)
            printf "Invalid input, try again.\n"
            ;;
    esac
done

SUBVOLS="@ @home @opt @root @srv @usr_local @var_cache @var_lib_libvirt_images @var_log @var_spool @var_tmp"
SUBVOL_PATHS="/mnt /mnt/home /mnt/opt /mnt/root /mnt/srv /mnt/usr/local /mnt/var/cache /mnt/var/lib/libvirt/images/ /mnt/var/log /mnt/var/spool /mnt/var/tmp"

printf "SUBVOLS=\"%s\"\nSUBVOL_PATHS=\"%s\"\n" "$SUBVOLS" "$SUBVOL_PATHS" >> "$VAR_FILE"

while :;do
    printf "Enter username for standard user: "
    read -r USERNAME
    USERNAME=$(printf "%s" "$USERNAME" | tr '[:upper:]' '[:lower:]')
    if [[ "$USERNAME" =~ ^[a-z_]([a-z0-9_-]{0,31}|[a-z0-9_-]{0,30}\$)$ ]];then #enforce username requirements
        printf "Create user: \"%s\"?\n[y/n]: " "$USERNAME"
        read -r USERNAME_CONF
        case "$USERNAME_CONF" in

            y)
                while :;do
                    until [ -n "$PASSWORD" ];do
                        printf "Enter password for %s: " "$USERNAME"
                        read -r PASSWORD
                    done
                    printf "Confirm Password for standard user: "
                    read -r PASSWD_CONF
                    case "$PASSWD_CONF" in

                        "$PASSWORD")
                            printf "USERNAME=\"%s\"\nPASSWORD=\"%s\"\n" "$USERNAME" "$PASSWORD" >> "$VAR_FILE"
                            break
                            ;;
                        *)
                            printf "PASSWORDS DID NOT MATCH!\n"
                            unset PASSWORD
                            ;;
                    esac
                done
                break
                ;;
            n)
                printf "Returning to user creation menu...\n\n"
                unset USERNAME
                break
                ;;
            *)
                printf "Invalid input, try again.\n"
                ;;
        esac
    else
        printf "Invalid username\n"
    fi
done

while :;do
    printf "Set root password? (Root account will be locked otherwise)\n[y/n]: "
    read -r RPASSWD
    case "$RPASSWD" in

        y)
            while :;do
                until [ -n "$ROOT_PASSWORD" ];do
                    printf "Enter password for root: "
                    read -r ROOT_PASSWORD
                done
                printf "Confirm Password for root: "
                read -r ROOT_PASSWD_CONF
                case "$ROOT_PASSWD_CONF" in

                "$ROOT_PASSWORD")
                    printf "ROOT_PASSWORD=\"%s\"\n" "$ROOT_PASSWORD" >> "$VAR_FILE"
                    break
                    ;;
                *)
                    printf "PASSWORDS DID NOT MATCH!\n"
                    unset ROOT_PASSWORD
                    ;;
                esac
            done
            break
            ;;
        n)
            break
            ;;
        *)
            printf "Invalid input, try again.\n"
            ;;
    esac
done

until [ "$PABIN" = y ] || [ "$PABIN" = n ];do
    printf "Install paru as a binary rather than compiling? (Faster install)\n[y/n]: "
    read -r PABIN
done
if [ "$PABIN" = y ];then
    PABIN=true;else
    PABIN=false
fi
printf "PABIN=%s\n" "$PABIN" >> "$VAR_FILE"

while :;do
    printf "Enter a hostname for this device: "
    read -r HOSTNAME
    HOSTNAME=$(printf "%s" "$HOSTNAME" | tr '[:upper:]' '[:lower:]')
    if [[ "$HOSTNAME" =~ ^[a-z][a-z0-9_.-]{0,62}[a-z0-9]$ ]];then #enforce hostname requirements
        while :;do
            printf "Use Hostname: \"%s\"?\n[y/n]: " "$HOSTNAME"
            read -r HN_CONF
            case "$HN_CONF" in

            y)
                printf "HN=\"%s\"\n" "$HOSTNAME" >> "$VAR_FILE"
                break 2
                ;;
            n)
                unset HOSTNAME
                break
                ;;
            *)
                printf "Invalid input, try again.\n"
                ;;
            esac
        done
    else
        printf "Invalid hostname.\n"
    fi
done

if [ "$ARTIX" = true ];then
    INIT=dinit
    printf "INIT=%s\n" "$INIT" >> "$VAR_FILE"
fi

while :;do
    printf "Install doas as a sudo replacement?\n[y/n]: "
    read -r DOAS
    case "$DOAS" in

    y)
        printf "DOAS=true\n" >> "$VAR_FILE"
        sed -i "/stuff/a alias sudo doas" "$HOME"/archix/config/fish/config.fish
        break
        ;;
    n)
        break
        ;;
    *)
        printf "Invalid input, try again.\n"
        ;;
    esac
done

until [ "$ADD_KERNELS" = n ];do
    unset ADD_KERNELS
    until [ "$KERNEL" = 1 ] || [ "$KERNEL" = 2 ] || [ "$KERNEL" = 3 ] || [ "$KERNEL" = 4 ] || [ "$KERNEL" = 5 ] || [ "$KERNEL" = 6 ];do
        printf "Which Linux kernel would you like to install? 1.Stock 2.LTS 3.Zen 4.Hardened 5.RT 6.RT-LTS\n[1,2,3,4,5,6]: "
        read -r KERNEL
    done

    if [ "$KERNEL" = 1 ];then
        KERNEL=linux
    elif [ "$KERNEL" = 2 ];then
        KERNEL=linux-lts
    elif [ "$KERNEL" = 3 ];then
        KERNEL=linux-zen
    elif [ "$KERNEL" = 4 ];then
        KERNEL=linux-hardened
    elif [ "$KERNEL" = 5 ];then
        KERNEL=linux-rt;else
        KERNEL=linux-rt-lts
    fi

    for i in $KERNELS;do
        if [ "$KERNEL" = "$i" ];then
            printf "ERROR: The %s kernel was already selected!\n" "$KERNEL"
            continue 2
        fi
    done

    if [ -z "$KERNELS" ];then
        KERNELS="$KERNEL";else
        KERNELS="$KERNELS $KERNEL"
    fi
    until [ "$ADD_KERNELS" = y ] || [ "$ADD_KERNELS" = n ];do
        printf "Install additional kernels? (Refind will be installed to manage boot entries if multiple kernels are installed)\n[y/n]: "
        read -r ADD_KERNELS
    done
done

if [ "$(printf "%s" "$KERNELS" | wc -w)" -gt 1 ];then
    REFIND=true
fi

if [ "$REFIND" = true ];then
    printf "REFIND=%s\n" "$REFIND" >> "$VAR_FILE"
fi
for i in $KERNELS;do
    if [ -z "$HEADERS" ];then
        HEADERS="${i}-headers";else
        HEADERS="$HEADERS ${i}-headers"
    fi
done
printf "KERNELS=\"%s\"\nHEADERS=\"%s\"\n" "$KERNELS" "$HEADERS" >> "$VAR_FILE"

find /usr/share/kbd/keymaps/ -type f -exec basename -s .map.gz {} \; | sed -e '/.inc/d' -e '/README/d' -e '/compose/d' -e '/.doc/d' -e '/.m4/d' -e '/hcesar/d' | sort > keymaps.txt

while :;do
    printf "Configuring console keymap: Use 'us' keyboard layout (default)?\n[y/n]: "
    read -r KEYMAPCONF
    case "$KEYMAPCONF" in
        y)
            KEYMAP=us
            break
            ;;
        n)
            while :;do
                printf "Enter keyboard keymap to use. Type 'list' to show available keymaps: "
                read -r CUSTKEYMAP
                if [ "$CUSTKEYMAP" = "list" ];then
                    less keymaps.txt
                elif ! grep -qx "$CUSTKEYMAP" keymaps.txt;then
                    printf "Please enter a valid keymap!\n"
                else
                    while :;do
                        printf "Use the '%s' keymap?\n[y/n]: " "$CUSTKEYMAP"
                        read -r CUSTKEYMAPCONF
                        case "$CUSTKEYMAPCONF" in

                            y)
                                KEYMAP=$CUSTKEYMAP
                                break 3
                                ;;
                            n)
                                break
                                ;;
                            *)
                                printf "Invalid input, try again.\n"
                                ;;
                        esac
                    done
                fi
            done
            ;;
        *)
            printf "Invalid input, try again.\n"
            ;;
    esac
done
printf "KEYMAP=%s\n" "$KEYMAP" >> "$VAR_FILE"

while :;do
    printf "Configure mkinitcpio to create a fallback image? (image will be stored at /efi/EFI/BOOT/BOOTx64.efi if refind is not installed)\n[y/n]: "
    read -r FALLBACK
    case "$FALLBACK" in

    y)
        printf "FALLBACK=true\n" >> "$VAR_FILE"
        break
        ;;
    n)
        break
        ;;
    *)
        printf "Invalid input, try again.\n"
        ;;
    esac
done
