#!/bin/sh
REPO="$HOME"/archix
VAR_FILE="$REPO"/scripts/vars
if ! [ -f "$VAR_FILE" ];then
    touch "$VAR_FILE"
fi

printf "REPO=%s\n" "$REPO" >> "$VAR_FILE"

pacman-key --init
pacman-key --populate
pacman -Sy --noconfirm mokutil

if mokutil --sb-state | grep "Setup Mode";then
    until [ "$SB" = y ] || [ "$SB" = n ];do
        printf "Detected Secure Boot in setup mode. Use Secure Boot?\n[y/n]: "
        read SB
    done;else
    SB=n
fi
if [ "$SB" = y ];then
    printf "SB=true\n" >> "$VAR_FILE";else
    printf "SB=false\n" >> "$VAR_FILE"
fi
if grep -qi "Artix" /etc/os-release;then
    ARTIX=true
    printf "ARTIX=true\n" >> "$VAR_FILE" 
fi

CHASSIS=$(cat /sys/class/dmi/id/chassis_type)
if [ "$CHASSIS" = 9 ] || [ "$CHASSIS" = 10 ];then
    printf "LAPTOP=true\n" >> "$VAR_FILE"
fi

if lscpu | grep -q "AuthenticAMD";then
    printf "CPU=amd\n" >> "$VAR_FILE"
elif lscpu | grep -q "GenuineIntel";then
    printf "CPU=intel\n" >> "$VAR_FILE"
fi

TIMEZONE=$(curl -s https://ipapi.co/timezone)
COUNTRY=$(printf "%s" "$TIMEZONE" | cut -d/ -f1)
printf "TIMEZONE=%s\nCOUNTRY=%s\n" "$TIMEZONE" "$COUNTRY" >> "$VAR_FILE"

DISKS=$(lsblk -no TYPE,KNAME,SIZE | awk '$1=="disk"{print "/dev/"$2" | "$3}')
while :;do
    unset INSTALL_DISK VAL_DISK DRIVE_CONF DISK_PICK
    printf "From the following, select the disk to install on:\n%s\nDisk name: " "$DISKS"
    read INSTALL_DISK
    for DISK in $(printf "%s" "$DISKS" | cut -d\  -f1);do
        if [ "$INSTALL_DISK" = "$DISK" ];then
            VAL_DISK=true
        fi
    done
    if [ "$VAL_DISK" = true ];then
        until [ "$DRIVE_CONF" = y ] || [ "$DRIVE_CONF" = n ];do
            printf "Install Linux on \"%s\"? THIS WILL FORMAT AND DELETE ALL DATA!\n[y/n]: " "$INSTALL_DISK"
            read DRIVE_CONF
        done
        if [ "$DRIVE_CONF" = y ];then
            break;else
            until [ "$DISK_PICK" = y ] || [ "$DISK_PICK" = n ];do
                printf "Pick another disk for installation?\n[y/n]: "
                read DISK_PICK
            done
            if [ "$DISK_PICK" = y ];then
                continue;else
                printf "EXITING INSTALLATION DUE TO NO INSTALL DISK PICKED...\n"
                exit 1
            fi
        fi;else
        printf "\"%s\" is not a valid installation disk!\n" "$INSTALL_DISK"
        continue
    fi
done

WINCHECK_DISKS=$(printf "%s" "$DISKS" | sed "s,$INSTALL_DISK,,")
for DISK in $WINCHECK_DISKS;do
    if efibootmgr "$DISK" | grep -q "Microsoft basic data";then
        printf "Windows installation detected on %s! Installing refind for dual-boot support..." "$DISK"
        REFIND=true
        sleep 5
        break
    fi
done

if grep -q 0 /sys/block/$(printf "%s" "$INSTALL_DISK" | cut -d/ -f3)/queue/rotational;then
    SSD=true;else
    SSD=false
fi
printf "INSTALL_DISK=%s\nSSD=%s\n" "$INSTALL_DISK" "$SSD" >> "$VAR_FILE"

until [ "$LUKS" = y ] || [ "$LUKS" = n ];do
    printf "Encrypt root with LUKS?\n[y/n]: "
    read LUKS
done
if [ "$LUKS" = y ];then
    printf "LUKS=true\n" >> "$VAR_FILE"
    while :;do
        unset LUKS_PASSWORD LUKS_PASSWD_CONF
        until [ -n "$LUKS_PASSWORD" ];do
            printf "Encryption password: "
            read LUKS_PASSWORD
        done
        until [ -n "$LUKS_PASSWD_CONF" ];do
            printf "Confirm encryption password: "
            read LUKS_PASSWD_CONF
        done
        if [ "$LUKS_PASSWORD" = "$LUKS_PASSWD_CONF" ];then
            printf "LUKS_PASSWORD=\"%s\"\n" "$LUKS_PASSWORD" >> "$VAR_FILE"
            break;else
            printf "PASSWORDS DID NOT MATCH!\n"
            continue
        fi
    done;else
    printf "LUKS=false\n" >> "$VAR_FILE"
fi

SUBVOLS="@ @home @var_cache @var_log @var_libvirt_images"
SUBVOL_PATHS="/mnt /mnt/home /mnt/var/cache /mnt/var/log /mnt/var/lib/libvirt/images"
#until [ "$REC_VOLS" = y ] || [ "$REC_VOLS" = n ];do
#    printf "Use premade subvolume layout? [y/n]: "
#    read REC_VOLS
#done
#if [ "$REC_VOLS" = y ];then
#    SUBVOLS="@ @home @var_cache @var_log @var_libvirt_images"
#    SUBVOL_PATHS="/mnt /mnt/home /mnt/var/cache /mnt/var/log /mnt/var/lib/libvirt/images"
#elif [ "$REC_VOLS" = n ];then
#    until [ "$NEW_SUBVOL" = n ];do
#        unset NEW_SUBVOL SUBVOL_NAME SUBVOL_PATH SUBVOL_CONF
#        until [ -n "$SUBVOL_NAME" ];do
#            printf "Name of subvolume: "
#            read SUBVOL_NAME
#        done
#        for i in $SUBVOLS;do
#            if [ "$SUBVOL_NAME" = "$i" ];then
#                printf "A subvolume by the name \"%s\" already exists!\n" "$SUBVOL_NAME"
#                continue 2
#            fi
#        done
#        until [ -n "$SUBVOL_PATH" ];do
#            printf "Mount point for the \"%s\" subvolume. E.g /mnt/home\n" "$SUBVOL_NAME"
#            read SUBVOL_PATH
#        done
#        for i in $SUBVOL_PATHS;do
#            if [ "$SUBVOL_PATH" = "$i" ];then
#                printf "The mount point: \"%s\" is already in use!\n" "$SUBVOL_PATH"
#                continue 2
#            fi
#        done
#        until [ "$SUBVOL_CONF" = y ] || [ "$SUBVOL_CONF" = n ];do
#            printf "Create subvolume: \"%s\" to be mounted at: \"%s\"?\n[y/n]: " "$SUBVOL_NAME" "$SUBVOL_PATH"
#            read SUBVOL_CONF
#        done
#        if [ "$SUBVOL_CONF" = y ];then
#            if [ -z "$SUBVOLS" ];then
#                SUBVOLS="$SUBVOL_NAME";else
#                SUBVOLS="$SUBVOLS $SUBVOL_NAME"
#            fi
#            if [ -z "$SUBVOL_PATHS" ];then
#                SUBVOL_PATHS="$SUBVOL_PATH";else
#                SUBVOL_PATHS="$SUBVOL_PATHS $SUBVOL_PATH"
#            fi
#            until [ "$NEW_SUBVOL" = y ] || [ "$NEW_SUBVOL" = n ];do
#                printf "Create another subvolume?\n[y/n]: "
#                read NEW_SUBVOL
#            done
#            if [ "$NEW_SUBVOL" = y ];then
#                continue
#            fi
#            fi
#    done
#fi
#printf "SUBVOLS=\"%s\"\nSUBVOL_PATHS=\"%s\"\n" "$SUBVOLS" "$SUBVOL_PATHS" >> "$VAR_FILE"

if [ -n "$SUBVOLS" ];then
    until [ "$SNAPPER" = y ] || [ "$SNAPPER" = n ];do
        printf "Install snapper for automated subvolume snapshots?\n[y/n]: "
        read SNAPPER
    done
    if [ "$SNAPPER" = y ];then
        SNAPPER=true;else
        SNAPPER=false
    fi
    printf "SNAPPER=%s\n" "$SNAPPER" >> "$VAR_FILE"
    if [ "$SNAPPER" = true ];then
        for i in $SUBVOLS;do
            unset SNAP_CONF
            SNAP_MOUNT_POINT=$(printf "%s" "$SUBVOL_PATHS" | cut -d\  -f1)
            until [ "$SNAP_CONF" = y ] || [ "$SNAP_CONF" = n ];do
                printf "Make Snapper config for subvolume: \"%s\" mounted at \"%s\"?\n[y/n]: " "$i" "$SNAP_MOUNT_POINT"
                read SNAP_CONF
            done
            if [ "$SNAP_CONF" = y ];then
                if [ -z "$SNAPPER_CONFIGS" ];then
                    SNAPPER_CONFIGS="$i";else
                    SNAPPER_CONFIGS="$SNAPPER_CONFIGS $i"
                fi
            fi
            SUBVOL_PATHS=$(printf "%s" "$SUBVOL_PATHS" | cut -d\  -f 2-)
        done
        printf "SNAPPER_CONFIGS=\"%s\"\n" "$SNAPPER_CONFIGS" >> "$VAR_FILE"
    fi

fi

until [ "$UN_CONF" = y ];do
    unset UN_CONF USERNAME
    until [ -n "$USERNAME" ];do
        printf "Username for standard user: "
        read USERNAME
    done
    until [ "$UN_CONF" = y ] || [ "$UN_CONF" = n ];do
        printf "Create user: \"%s\"?\n[y/n]: " "$USERNAME"
        read UN_CONF
    done
done

while :;do
    unset PASSWORD PASSWD_CONF
    until [ -n "$PASSWORD" ];do
        printf "Password for standard user: "
        read PASSWORD
    done
    until [ -n "$PASSWD_CONF" ];do
        printf "Confirm Password for standard user: "
        read PASSWD_CONF
    done
    if [ "$PASSWORD" = "$PASSWD_CONF" ];then
        break;else
        printf "PASSWORDS DID NOT MATCH!\n"
        continue
    fi
done
printf "USERNAME=\"%s\"\nPASSWORD=\"%s\"\n" "$USERNAME" "$PASSWORD" >> "$VAR_FILE"

until [ "$RPASSWD" = y ] || [ "$RPASSWD" = n ];do
    printf "Set root password? (Root account will be locked otherwise)\n[y/n]: "
    read RPASSWD
done
if [ "$RPASSWD" = y ];then
    while :;do
        unset ROOT_PASSWORD ROOT_PASSWD_CONF
        until [ -n "$ROOT_PASSWORD" ];do
            printf "Password for root: "
            read ROOT_PASSWORD
        done
        until [ -n "$ROOT_PASSWD_CONF" ];do
            printf "Confirm Password for root: "
            read ROOT_PASSWD_CONF
        done
        if [ "$ROOT_PASSWORD" = "$ROOT_PASSWD_CONF" ];then
            printf "ROOT_PASSWORD=\"%s\"\n" "$ROOT_PASSWORD" >> "$VAR_FILE"
            break;else
            printf "PASSWORDS DID NOT MATCH!\n"
            continue
        fi
    done
fi

printf "ROOT_PASSWORD=\"%s\"\n" "$ROOT_PASSWORD" >> "$VAR_FILE"

until [ "$PABIN" = y ] || [ "$PABIN" = n ];do
    printf "Install paru as a binary rather than compiling? (Faster install)\n[y/n]: "
    read PABIN
done
if [ "$PABIN" = y ];then
    PABIN=true;else
    PABIN=false
fi
printf "PABIN=%s\n" "$PABIN" >> "$VAR_FILE"

until [ "$HN_CONF" = y ];do
    unset HN_CONF HN
    until [ -n "$HN" ];do
        printf "Enter Hostname for install: "
        read HN
    done
    until [ "$HN_CONF" = y ] || [ "$HN_CONF" = n ];do
        printf "Use Hostname: \"%s\"?\n[y/n]: " "$HN"
        read HN_CONF
    done
done
printf "HN=\"%s\"\n" "$HN" >> "$VAR_FILE"

if [ "$ARTIX" = true ];then
    #until [ "$INIT" = 1 ] || [ "$INIT" = 2 ] || [ "$INIT" = 3 ] || [ "$INIT" = 4 ];do
    #    printf "Which init system to install? 1.openrc 2.runit 3.dinit 4.s6\n[1,2,3,4]: "
    #    read INIT
    #done
    #if [ "$INIT" = 1 ];then
    #    INIT=openrc
    #elif [ "$INIT" = 2 ];then
    #    INIT=runit
    #elif [ "$INIT" = 3 ];then
    #    INIT=dinit;else
    #    INIT=s6
    #fi
    INIT=dinit
    printf "INIT=%s\n" "$INIT" >> "$VAR_FILE"
fi
until [ "$DOAS" = y ] || [ "$DOAS" = n ];do
    printf "Install doas as a sudo replacement?\n[y/n]: "
    read DOAS
done
if [ "$DOAS" = y ];then
    DOAS=true
    sed -i "/stuff/a alias sudo doas" "$HOME"/archix/config/fish/config.fish
elif [ "$DOAS" = n ];then
    DOAS=false
fi
printf "DOAS=%s\n" "$DOAS" >> "$VAR_FILE"

until [ "$ADD_KERNELS" = n ];do
    unset ADD_KERNELS
    until [ "$KERNEL" = 1 ] || [ "$KERNEL" = 2 ] || [ "$KERNEL" = 3 ] || [ "$KERNEL" = 4 ] || [ "$KERNEL" = 5 ] || [ "$KERNEL" = 6 ];do
        printf "Which Linux kernel would you like to install? 1.Stock 2.LTS 3.Zen 4.Hardened 5.RT 6.RT-LTS\n[1,2,3,4,5,6]: "
        read KERNEL
    done

    if [ "$KERNEL" = 1 ];then
        KERNEL=linux
    elif [ "$KERNEL" = 2 ];then
        KERNEL=linux-lts
    elif [ "$KERNEL" = 3 ];then
        KERNEL=linux-zen
    elif [ "$KERNEL" = 4 ];then
        KERNEL=linux-hardened
    elif [ "$KERNEL" = 5 ];then
        KERNEL=linux-rt;else
        KERNEL=linux-rt-lts
    fi

    for i in $KERNELS;do
        if [ "$KERNEL" = "$i" ];then
            printf "ERROR: The %s kernel was already selected!\n" "$KERNEL"
            continue 2
        fi
    done

    if [ -z "$KERNELS" ];then
        KERNELS="$KERNEL";else
        KERNELS="$KERNELS $KERNEL"
    fi
    until [ "$ADD_KERNELS" = y ] || [ "$ADD_KERNELS" = n ];do
        printf "Install additional kernels? (Refind will be installed to manage boot entries if multiple kernels are installed)\n[y/n]: "
        read ADD_KERNELS
    done
done

if [ $(printf "%s" "$KERNELS" | wc -w) -gt 1 ];then
    REFIND=true
fi

if [ "$REFIND" = true ];then
    printf "REFIND=%s\n" "$REFIND" >> "$VAR_FILE"
fi
for i in $KERNELS;do
    if [ -z "$HEADERS" ];then
        HEADERS="${i}-headers";else
        HEADERS="$HEADERS ${i}-headers"
    fi
done
printf "KERNELS=\"%s\"\nHEADERS=\"%s\"\n" "$KERNELS" "$HEADERS" >> "$VAR_FILE"

find /usr/share/kbd/keymaps/ -type f -exec basename -s .map.gz {} \; | sed -e '/.inc/d' -e '/README/d' -e '/compose/d' -e '/.doc/d' -e '/.m4/d' -e '/hcesar/d' | sort > keymaps.txt

until [ "$KEYMAPCONF" = y ] || [ "$KEYMAPCONF" = n ];do
    printf "Configuring console keymap: Use 'us' keyboard layout (default)?\n[y/n]: "
    read KEYMAPCONF
done
if [ "$KEYMAPCONF" = y ];then
    KEYMAP=us
elif [ "$KEYMAPCONF" = n ];then
    while true;do
        unset CUSTKEYMAPCONF
        printf "Enter keyboard keymap to use. Type 'list' to show available keymaps: "
        read CUSTKEYMAP
        if [ "$CUSTKEYMAP" = "list" ];then
            less keymaps.txt
        elif ! grep -x "$CUSTKEYMAP" keymaps.txt;then
            printf "Please enter a valid keymap!\n"
        else
            until [ "$CUSTKEYMAPCONF" = y ] || [ "$CUSTKEYMAPCONF" = n ];do
                printf "Use the '%s' keymap?\n[y/n]: " "$CUSTKEYMAP"
                read CUSTKEYMAPCONF
            done
            if [ "$CUSTKEYMAPCONF" = y ];then
                KEYMAP=$CUSTKEYMAP
                break
            fi
        fi
    done
fi
printf "KEYMAP=%s\n" "$KEYMAP" >> "$VAR_FILE"

until [ "$FALLBACK" = y ] || [ "$FALLBACK" = n ];do
    printf "Configure mkinitcpio to create a fallback image? (image will be stored at /efi/EFI/BOOT/BOOTx64.efi if refind is not installed)\n[y/n]: "
    read FALLBACK
done
if [ "$FALLBACK" = y ];then
    FALLBACK=true
elif [ "$FALLBACK" = n ];then
    FALLBACK=false
fi
printf "FALLBACK=%s\n" "$FALLBACK" >> "$VAR_FILE"

printf "SUBVOLS=\"%s\"\nSUBVOL_PATHS=\"%s\"\n" "$SUBVOLS" "$SUBVOL_PATHS" >> "$VAR_FILE"
