#Improve compatability by increasing memory map count
vm.max_map_count=2147483642

#Make kernel more likely to release memory being used for VFS cache
vm.vfs_cache_pressure=50

#Bias for the kernel to use swap (Higher means swapping is more likely)
vm.swappiness=180

#Optimise zram performance
vm.watermark_boost_factor=0
vm.watermark_scale_factor=125
vm.page-cluster=0
